### PR TITLE
fix: Multiple token fetches resolved

### LINKED ISSUE #3: Multiple calls to getToken
Starting the CDN when there are multiple submissions to upload towards BFarm leads to multiple occurences in the log of: "Getting API token" in quick succession

This indicates that the token for upload is fetched multiple times when it is supposed to be reused.

### PR DESCRIPTION
**Pull request by apothecarius**
The caching of tokens for communication with the BFarm node previously wasn't functioning properly, because whether getToken returned a cached value or a fresh value depended on the cache being set. When multiple uploads would happen asynchronously, all of them would not find a cached token and request a new one simultaneously.

This wraps the token fetch into a Promise that is returned for all the subsequent calls to getToken. That also means that subsequent calls might end up with a failed future for token(!)

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved connector authentication: more reliable token caching, proactive invalidation before expiry, and clearer handling of failed uploads.

* **Tests**
  * Added a comprehensive test suite validating token lifecycle and upload outcomes.
  * Renamed several test classes for clarity and maintainability.
  * Added test fixtures to exercise authentication and upload scenarios.

* **Chores**
  * Updated ignore rules to exclude an additional build artifact.
  * Added a mocking library to support expanded test coverage.

### CODE REVIEW

File: connectors/src/main/scala/de/dnpm/ccdn/connector/BfArMConnectorImpl.scala [hunk 1]
```diff
@@ -145,46 +145,29 @@ with Logging
...
-
-        case Success(Left(err)) =>
-          log.error(s"Failed to get BfArM API token: ${err.statusCode} ${err.error}: ${err.message}")
-
+        case Success(tkn) =>
+          // Schedule token removal after its expiration
+          executor.schedule(expireToken, tkn.expires_in - 5, SECONDS)
         case Failure(t) =>
           log.error("Failed to get BfArM API token",t)
       }
```
[the remark this answers is not in the document]
Comment (apothecarius) [reply connectors/src/main/scala/de/dnpm/ccdn/connector/BfArMConnectorImpl.scala:166]: Will fix after the case is covered with unit test

File: connectors/src/test/scala/de/dnpm/ccdn/connector/BfArMConnectorImplTests.scala [hunk 2]
```diff
@@ -0,0 +1,139 @@
...
+
+  it must "only fetch one token to make multiple uploads in short time" in {
+    prepAuthMocks()
+    assert(tokenFetchCounter.get() == 0)
+    val submissionReports = List.fill(nUploads)(makeFakeReport)
+
+    for {
+      _ <- Future.traverse(submissionReports)(toTest.upload)
+    } yield tokenFetchCounter.get mustBe 1
+    assert(tokenFetchCounter.get() == 1)
```
Comment (lucienclin) [inline connectors/src/test/scala/de/dnpm/ccdn/connector/BfArMConnectorImplTests.scala]: This is redundant: the line just above performs the exact same check, leading to Future[Assertion] whose outcome represents the test result. So might as well remove it.

File: connectors/src/test/scala/de/dnpm/ccdn/connector/BfArMConnectorImplTests.scala [hunk 3]
```diff
@@ -0,0 +1,139 @@
...
+    Json.obj(
+      "access_token" -> "babelub",
+      "expires_in" -> tokenExpiration,
+      "refresh_expires_in" -> tokenExpiration,
+      "scope" -> "monocle",
+      "token_type" -> "asdbest")
+
+
+  //Auth mocks
+  private def prepAuthMocks(tokenExpiration:Int=133742) = {
```
Comment (lucienclin) [inline connectors/src/test/scala/de/dnpm/ccdn/connector/BfArMConnectorImplTests.scala]: Nitpicking, but:

This method is used only twice and only within this test class. Using a default value here doesn't add any real value i.m.h.o, but rather makes it harder to understand why it's called as prepAuthMocks() in one case, but prepAuthMocks(N) in the other.

Also, as we discussed seemingly "magic numbers" yesterday, the default value seems "magic" indeed because it's not obvious why it has this particular, seemingly random value.

I'd suggest removing the default value, and calling it as e.g. "prepAuthMocks(600)" with a comment explaining that the token is supposed to last long enough (10 min) in the test that only one is fetched on multiple sequenced uploads.

File: connectors/src/test/scala/de/dnpm/ccdn/connector/BfArMConnectorImplTests.scala [hunk 4]
```diff
@@ -0,0 +1,139 @@
...
+  it must "fetch a new token for subsequent uploads if it expires during a series of uploads" in {
+    prepAuthMocks(5)
+    assert(tokenFetchCounter.get() == 0)
+    toTest.upload(makeFakeReport) //TODO muss auf die Zukunft warten
+    assert(tokenFetchCounter.get() == 1)
+    toTest.upload(makeFakeReport)
+    assert(tokenFetchCounter.get() == 2)
+  }
+
+  "Token" must "be deserializable from the JSON fields that sent from BfArM" in {
```
Comment (lucienclin) [inline connectors/src/test/scala/de/dnpm/ccdn/connector/BfArMConnectorImplTests.scala:209]: Design style nitpicking:

As discussed, i.m.h.o it would be cleaner to use the Token DTO in this test instead of a manually assembled JsObject, as suggested here: https://github.com/dnpm-dip/central-data-node/blob/0344fe164dc0d9d94b6956f3ca20023fbfc16821/connectors/src/test/scala/de/dnpm/ccdn/connector/BfArMConnectorTests.scala#L52-L62

Then this specific test here could be reduced to ensuring that a Token DTO instance serialized with the OWrtites[Token] derived in this context (because the "main" code only needs to _read_ Token from JSON), can be correctly deserialized by its Reads[Token].

Along the lines of:
```
val token = Token(....)

// Test
val tokenResult = Json.fromJson[Token](Json.toJson(token))

assert(tokenResult.isSuccess) 
assert(tokenResult.get == token)  // case classes have a deep equals method
```

File: connectors/src/test/scala/de/dnpm/ccdn/connector/BfArMConnectorImplTests.scala [hunk 5]
```diff
@@ -0,0 +1,139 @@
...
+
+    for {
+      _ <- Future.traverse(submissionReports)(toTest.upload)
+    } yield tokenFetchCounter.get mustBe 1
+    assert(tokenFetchCounter.get() == 1)
+  }
+
+  it must "fetch a new token for subsequent uploads if it expires during a series of uploads" in {
+    prepAuthMocks(5)
+    assert(tokenFetchCounter.get() == 0)
```
Comment (lucienclin) [inline connectors/src/test/scala/de/dnpm/ccdn/connector/BfArMConnectorImplTests.scala]: Just a general style suggestion:
Consider using ScalaTest's matchers (https://www.scalatest.org/user_guide/using_matchers) instead of always reducing checks to `assert(boolean condition)`. The matchers often make for easier reading of what's checked. But that's a matter of trade-off -- sometimes the matchers look/feel more idiomatic, sometines simple asserts.

File: connectors/src/test/scala/de/dnpm/ccdn/connector/BfArMConnectorImplTests.scala [hunk 6]
```diff
@@ -0,0 +1,139 @@
...
+      Oncological,
+      LibraryType.WGSLr,
+      HealthInsurance.Type.UNK
+    )
+  }
+
+  //how many documents are uploaded
+  val nUploads = 10
+  //increments every time a token is fetched, should increase once
+  val tokenFetchCounter = new AtomicInteger(0)
```
Comment (lucienclin) [inline connectors/src/test/scala/de/dnpm/ccdn/connector/BfArMConnectorImplTests.scala]: Just a suggestion:
ScalaMock stubs apparently allow to check the number of times they were called: https://scalamock.org/stubs/features/#calls-and-times
So, also as an incentive to further explore ScalaMock, this test setup could possibly be redesigned around this built-in functionality by checking directly how many times a stub was called, instead of explicitly using the AtomicInteger counter incremented as a side effect in the one stub's `.onCall(...)` (Line 85).

File: connectors/src/test/scala/de/dnpm/ccdn/connector/BfArMConnectorImplTests.scala [hunk 7]
```diff
@@ -0,0 +1,139 @@
...
+      "token_type" -> "asdbest")
+
+
+  //Auth mocks
+  private def prepAuthMocks(tokenExpiration:Int=133742) = {
+    val pseudoToken:JsValue = makeToken(tokenExpiration)
+    tokenFetchCounter.set(0)
+    val mockAuthRequest = stub[CustomRequest]
+    val mockAuthResponse = stub[mockAuthRequest.Response]
+    (mockHttpClient.url _).when("authURL").returns(mockAuthRequest)
```
Comment (lucienclin) [inline connectors/src/test/scala/de/dnpm/ccdn/connector/BfArMConnectorImplTests.scala]: Here and in the corresponding stub for submission report upload, there is a hard-coded String "authURL" and "apiURL", but the exact same values are already used in the instantiation of the Config object used in the BfArMConnectorImpl (line 44). 

This duplication of hard-coded values bears the potential for them to run out of sync, for instance if the values in the Config were changed. Thus I'd argue it's cleaner to use the values from the Config in the stub setup, like in the demo:
https://github.com/dnpm-dip/central-data-node/blob/0344fe164dc0d9d94b6956f3ca20023fbfc16821/connectors/src/test/scala/de/dnpm/ccdn/connector/BfArMConnectorTests.scala#L97C25-L97C39

File: connectors/src/test/scala/de/dnpm/ccdn/connector/BfArMConnectorImplTests.scala (hunk 5 above)
Comment (apothecarius) [reply connectors/src/test/scala/de/dnpm/ccdn/connector/BfArMConnectorImplTests.scala]: Will use assertResult where applicable and will use the clue parameter where necessary

File: connectors/src/test/scala/de/dnpm/ccdn/connector/BfArMConnectorImplTests.scala (hunk 3 above)
Comment (apothecarius) [reply connectors/src/test/scala/de/dnpm/ccdn/connector/BfArMConnectorImplTests.scala]: I will comment where numbers are picked randomly.

File: connectors/src/test/scala/de/dnpm/ccdn/connector/BfArMConnectorImplTests.scala (hunk 4 above)
Comment (apothecarius) [reply connectors/src/test/scala/de/dnpm/ccdn/connector/BfArMConnectorImplTests.scala:209]: applied

File: connectors/src/test/scala/de/dnpm/ccdn/connector/BfArMConnectorImplTests.scala (hunk 6 above)
Comment (apothecarius) [reply connectors/src/test/scala/de/dnpm/ccdn/connector/BfArMConnectorImplTests.scala]: The supplied link uses a different testing framework. Getting the number of calls doesn't seem to be supported directly.

File: connectors/src/main/scala/de/dnpm/ccdn/connector/BfArMConnectorImpl.scala [hunk 8]
```diff
@@ -145,46 +156,30 @@ with Logging
...
-          log.info(s"Updating API token reference and scheduling expiration in ${tkn.expires_in} s")
-          token.set(Some(tkn))
-          executor.schedule(expire, tkn.expires_in - 5, SECONDS)
-
-        case Success(Left(err)) =>
-          log.error(s"Failed to get BfArM API token: ${err.statusCode} ${err.error}: ${err.message}")
-
+        case Success(tkn) =>
+          // Schedule token removal after its expiration
+          executor.schedule(clearToken, tkn.expires_in - 5, SECONDS)
```
[the remark this answers is not in the document]
Comment (apothecarius) [reply connectors/src/main/scala/de/dnpm/ccdn/connector/BfArMConnectorImpl.scala:163]: That's a good thing

File: connectors/src/test/scala/de/dnpm/ccdn/connector/BfArMConnectorImplTests.scala [hunk 9]
```diff
@@ -0,0 +1,207 @@
...
+    for {
+      _ <- (assertResult(0, "Tokenfetchcounter should be initialized to zero before test")
+              (fixture.tokenFetchCounter.get()))
+      _ <- fixture.toTest.upload(makeFakeReport)
+      _ <- assertResult(1, "Tokenfetch appearantly did not tirgger")(fixture.tokenFetchCounter.get())
+      _ <- fixture.toTest.upload(makeFakeReport)
+      _ <- assertResult(2)(fixture.tokenFetchCounter.get()) //no clue why it failed
+      _ <- fixture.toTest.upload(makeFakeReport)
+      _ <- assertResult(3)(fixture.tokenFetchCounter.get())
+    } yield succeed
```
[the remark this answers is not in the document]
Comment (apothecarius) [reply connectors/src/test/scala/de/dnpm/ccdn/connector/BfArMConnectorImplTests.scala:163]: Coderabbit said above that this would actually trigger immediately. Hasn't failed yet either, so I'll leave it as is.
Will add a comment for the future, in case this should actually fail randomly some time.

File: connectors/src/main/scala/de/dnpm/ccdn/connector/BfArMConnectorImpl.scala [hunk 10]
```diff
@@ -145,46 +156,30 @@ with Logging
...
-  ): Future[WSRequest] =
-    token.get
-      .fold(
-        getToken
-      )(
-        Future.successful
-      )
+  ): Future[WSRequest] = {
+    tokenCache.updateAndGet(curVal => curVal.recoverWith{
+        case _:Exception => fetchToken
```
Comment (lucienclin) [inline connectors/src/main/scala/de/dnpm/ccdn/connector/BfArMConnectorImpl.scala]: Nitpick:
This is correct code, but given the "catch all" partial function, the syntax
```
...recoverWith {
  case t => fetchToken
}
```
would be more idiomatic i.m.h.o.

File: connectors/src/test/scala/de/dnpm/ccdn/connector/BfArMConnectorImplTests.scala (hunk 4 above)
Comment (lucienclin) [reply connectors/src/test/scala/de/dnpm/ccdn/connector/BfArMConnectorImplTests.scala:209]: Maybe I wasn't clear enough, but apparently you didn't get the meaning of the suggestion to use the deep equality method of case classes, given that the multiple explicit checks of individual properties (L204-L209) are still there:
For each case class, the compiler generates an .equals(...) method that performs a _deep equality_ check, i.e.
` testToken == deserializedToken.get` will be `true` iff each single property is equal on both instances. This allows to skip the multiple checks on each property.

File: connectors/src/test/scala/de/dnpm/ccdn/connector/BfArMConnectorImplTests.scala [hunk 11]
```diff
@@ -0,0 +1,211 @@
...
+      Oncological,
+      LibraryType.WGSLr,
+      HealthInsurance.Type.UNK
+    )
+  }
+
+  //how many documents are uploaded
+  val nUploads = 10
+  val LongTokenLifetime = 133742 //random amount of seconds long enough to run the test
+  val ZeroTokenLifetime = 5 //BfArMConnectorImpl clears the token 5 seconds before formal expiration
```
Comment (lucienclin) [inline connectors/src/test/scala/de/dnpm/ccdn/connector/BfArMConnectorImplTests.scala:45]: On reflection, this seems to couple the testing logic to internals of BfArMConnectorImpl, because this number only makes sense when knowing that token removal is indeed performed 5 s before expiration is due within BfArMConnectorImpl. 
Also, this relates to coderabbitai's hint at a potential issues with that logic, in case `expires_in - 5 < 0`. Maybe it would be cleaner to follow coderabbitai's comment and adapt BfArMConnectorImpl to handle such cases safely, then explicitly use a token with 0 s validity duration here?

Comment (apothecarius) [reply connectors/src/test/scala/de/dnpm/ccdn/connector/BfArMConnectorImplTests.scala:45]: Will set it to zero to ensure that the negative number space is covered by the timeout. Immediate token expiration is necessary for the unit tests, because tests need to run fast. Only alternative would be to manipulate time services, not sure if even possible in scalatest

File: connectors/src/main/scala/de/dnpm/ccdn/connector/BfArMConnectorImpl.scala (hunk 10 above)
Comment (apothecarius) [reply connectors/src/main/scala/de/dnpm/ccdn/connector/BfArMConnectorImpl.scala]: Valid

File: connectors/src/test/scala/de/dnpm/ccdn/connector/BfArMConnectorImplTests.scala (hunk 11 above)
Comment (apothecarius) [reply connectors/src/test/scala/de/dnpm/ccdn/connector/BfArMConnectorImplTests.scala:45]: Actually doesn't work with zero....

Comment (apothecarius) [reply connectors/src/test/scala/de/dnpm/ccdn/connector/BfArMConnectorImplTests.scala:45]: Zero lifetime is actually a race condition. Appearantly this is not executed in a blocking way, even if as fast as possible. Added 150 millisecond delay to the test that verifies automatic token refetch
